name: metadrive
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy-base=2.3.5
  - openjpeg=2.5.4
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pyparsing=3.2.5
  - python=3.13.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - decorator==5.2.1
      - idna==3.11
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lxml==6.0.2
      - markupsafe==3.0.3
      - msgpack==1.1.2
      - numpy==2.2.6
      - pexpect==4.9.0
      - pip==10.0.1
      - ptyprocess==0.7.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - urllib3==2.5.0
prefix: /home/antonioskorin/anaconda3/envs/metadrive
